import type { Dealership } from "@/lib/types";
import type { CanvasElement, Design } from "./types";
import { newId } from "./types";

export interface StarterTemplate {
  id: string;
  label: string;
  description: string;
  emoji: string;
  canvasSize: string;
  canvasWidth: number;
  canvasHeight: number;
  backgroundColor: string;
  build: (dealership: Dealership | null) => CanvasElement[];
}

function brand(d: Dealership | null) {
  return {
    primary: d?.brand_colors?.primary || "#0F2A47",
    secondary: d?.brand_colors?.secondary || "#FFFFFF",
    accent: d?.brand_colors?.accent || "#FF6B00",
  };
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
  {
    id: "ig-vehicle-spotlight",
    label: "Instagram Vehicle Spotlight",
    description: "Big photo top, headline + price below",
    emoji: "📸",
    canvasSize: "instagram-post",
    canvasWidth: 1080,
    canvasHeight: 1080,
    backgroundColor: "#0F2A47",
    build: (d) => {
      const c = brand(d);
      return [
        {
          id: newId(),
          type: "shape",
          shape: "rect",
          x: 0,
          y: 660,
          width: 1080,
          height: 420,
          rotation: 0,
          fill: c.primary,
        },
        {
          id: newId(),
          type: "text",
          text: "{{ymm}}",
          x: 60,
          y: 700,
          width: 960,
          height: 100,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 84,
          fontStyle: "bold",
          align: "left",
          fill: c.secondary,
          letterSpacing: 2,
        },
        {
          id: newId(),
          type: "text",
          text: "STARTING AT",
          x: 60,
          y: 820,
          width: 600,
          height: 30,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 22,
          fontStyle: "bold",
          align: "left",
          fill: c.accent,
          letterSpacing: 6,
        },
        {
          id: newId(),
          type: "text",
          text: "{{price}}",
          x: 60,
          y: 860,
          width: 600,
          height: 130,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 130,
          fontStyle: "bold",
          align: "left",
          fill: c.secondary,
        },
        {
          id: newId(),
          type: "text",
          text: "{{dealer_name}} · {{phone}}",
          x: 60,
          y: 1010,
          width: 960,
          height: 30,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 18,
          fontStyle: "normal",
          align: "left",
          fill: c.secondary,
          opacity: 0.7,
        },
      ];
    },
  },
  {
    id: "story-just-arrived",
    label: "Story: Just Arrived",
    description: "9:16 with stamp + CTA",
    emoji: "🚗",
    canvasSize: "instagram-story",
    canvasWidth: 1080,
    canvasHeight: 1920,
    backgroundColor: "#FFFFFF",
    build: (d) => {
      const c = brand(d);
      return [
        {
          id: newId(),
          type: "shape",
          shape: "rect",
          x: 60,
          y: 200,
          width: 960,
          height: 200,
          rotation: -8,
          fill: c.accent,
        },
        {
          id: newId(),
          type: "text",
          text: "JUST ARRIVED",
          x: 60,
          y: 240,
          width: 960,
          height: 130,
          rotation: -8,
          fontFamily: "Bebas Neue",
          fontSize: 130,
          fontStyle: "bold",
          align: "center",
          fill: c.secondary,
          letterSpacing: 6,
        },
        {
          id: newId(),
          type: "text",
          text: "{{ymm}}",
          x: 60,
          y: 1500,
          width: 960,
          height: 120,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 100,
          fontStyle: "bold",
          align: "center",
          fill: c.primary,
        },
        {
          id: newId(),
          type: "text",
          text: "{{price}}",
          x: 60,
          y: 1620,
          width: 960,
          height: 80,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 60,
          fontStyle: "bold",
          align: "center",
          fill: c.accent,
        },
        {
          id: newId(),
          type: "shape",
          shape: "rect",
          x: 240,
          y: 1740,
          width: 600,
          height: 96,
          rotation: 0,
          fill: c.primary,
          cornerRadius: 48,
        },
        {
          id: newId(),
          type: "text",
          text: "BOOK A TEST DRIVE",
          x: 240,
          y: 1768,
          width: 600,
          height: 50,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 32,
          fontStyle: "bold",
          align: "center",
          fill: c.secondary,
          letterSpacing: 4,
        },
      ];
    },
  },
  {
    id: "fb-price-drop",
    label: "Facebook Price Drop",
    description: "Burst + comparison price",
    emoji: "💥",
    canvasSize: "facebook-post",
    canvasWidth: 1080,
    canvasHeight: 1350,
    backgroundColor: "#FFFFFF",
    build: (d) => {
      const c = brand(d);
      return [
        {
          id: newId(),
          type: "shape",
          shape: "star",
          x: 540,
          y: 300,
          width: 540,
          height: 540,
          rotation: 0,
          fill: c.accent,
          numPoints: 16,
          innerRadius: 0.85,
        },
        {
          id: newId(),
          type: "text",
          text: "PRICE\nDROP",
          x: 290,
          y: 230,
          width: 500,
          height: 200,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 130,
          fontStyle: "bold",
          align: "center",
          fill: c.secondary,
          lineHeight: 0.95,
        },
        {
          id: newId(),
          type: "text",
          text: "{{ymm}}",
          x: 60,
          y: 800,
          width: 960,
          height: 100,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 84,
          fontStyle: "bold",
          align: "center",
          fill: c.primary,
        },
        {
          id: newId(),
          type: "text",
          text: "{{price}}",
          x: 60,
          y: 920,
          width: 960,
          height: 160,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 160,
          fontStyle: "bold",
          align: "center",
          fill: c.accent,
        },
        {
          id: newId(),
          type: "text",
          text: "{{dealer_name}} · {{phone}}",
          x: 60,
          y: 1240,
          width: 960,
          height: 30,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 20,
          fontStyle: "normal",
          align: "center",
          fill: c.primary,
        },
      ];
    },
  },
  {
    id: "billboard-seasonal",
    label: "Digital Billboard",
    description: "16:9 wide, seasonal tagline",
    emoji: "🪧",
    canvasSize: "digital-billboard",
    canvasWidth: 3840,
    canvasHeight: 2160,
    backgroundColor: "#0F2A47",
    build: (d) => {
      const c = brand(d);
      return [
        {
          id: newId(),
          type: "text",
          text: "SUMMER SAVINGS EVENT",
          x: 200,
          y: 700,
          width: 3440,
          height: 250,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 240,
          fontStyle: "bold",
          align: "center",
          fill: c.secondary,
          letterSpacing: 12,
        },
        {
          id: newId(),
          type: "text",
          text: "AT {{dealer_name}}",
          x: 200,
          y: 1000,
          width: 3440,
          height: 120,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 110,
          fontStyle: "bold",
          align: "center",
          fill: c.accent,
          letterSpacing: 12,
        },
        {
          id: newId(),
          type: "shape",
          shape: "rect",
          x: 1320,
          y: 1300,
          width: 1200,
          height: 240,
          rotation: 0,
          fill: c.accent,
          cornerRadius: 12,
        },
        {
          id: newId(),
          type: "text",
          text: "0% APR · 60 MOS",
          x: 1320,
          y: 1370,
          width: 1200,
          height: 120,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 110,
          fontStyle: "bold",
          align: "center",
          fill: c.secondary,
        },
        {
          id: newId(),
          type: "text",
          text: "{{phone}} · {{website}}",
          x: 200,
          y: 1900,
          width: 3440,
          height: 80,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 60,
          fontStyle: "normal",
          align: "center",
          fill: c.secondary,
          opacity: 0.8,
        },
      ];
    },
  },
  {
    id: "email-header-promo",
    label: "Email Header",
    description: "3:1 header for newsletters",
    emoji: "📧",
    canvasSize: "email-header",
    canvasWidth: 1500,
    canvasHeight: 500,
    backgroundColor: "#FFFFFF",
    build: (d) => {
      const c = brand(d);
      return [
        {
          id: newId(),
          type: "shape",
          shape: "rect",
          x: 0,
          y: 0,
          width: 1500,
          height: 500,
          rotation: 0,
          fill: c.primary,
        },
        {
          id: newId(),
          type: "text",
          text: "WEEKEND SALES EVENT",
          x: 60,
          y: 180,
          width: 1380,
          height: 100,
          rotation: 0,
          fontFamily: "Bebas Neue",
          fontSize: 84,
          fontStyle: "bold",
          align: "center",
          fill: c.secondary,
          letterSpacing: 6,
        },
        {
          id: newId(),
          type: "text",
          text: "Save up to $5,000 on featured inventory",
          x: 60,
          y: 290,
          width: 1380,
          height: 50,
          rotation: 0,
          fontFamily: "Inter",
          fontSize: 28,
          fontStyle: "normal",
          align: "center",
          fill: c.accent,
        },
      ];
    },
  },
];

export function templateToDesign(t: StarterTemplate, dealership: Dealership | null): Partial<Design> {
  return {
    name: t.label,
    kind: "draft",
    canvasSize: t.canvasSize,
    canvasWidth: t.canvasWidth,
    canvasHeight: t.canvasHeight,
    backgroundColor: t.backgroundColor,
    elements: t.build(dealership),
  };
}
