import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";

const KIE_CHAT_URL = "https://api.kie.ai/gpt-5-2/v1/chat/completions";

type ReplyTone = "excited" | "informative" | "closing";

const TONE_INSTRUCTIONS: Record<ReplyTone, string> = {
  excited:
    "Warm, enthusiastic, and personable. Open with energy. Mirror the customer's excitement. Short paragraphs. End with an easy next step.",
  informative:
    "Helpful, factual, and reassuring. Lead with the answer to their question. Include 2–3 concrete vehicle details. Avoid hype. Offer a clear next step.",
  closing:
    "Confident and conversion-focused. Acknowledge their interest, surface urgency (recent interest in this unit, limited inventory, today's pricing), and propose a specific action (test drive, hold deposit, soft credit pull). Stay respectful and never pushy.",
};

const SYSTEM_PROMPT = `You are an experienced automotive sales BDC (Business Development Center) agent.
Your job: write a single, ready-to-send email/SMS reply to a customer inquiry from Cars.com, AutoTrader, Facebook Marketplace, or the dealership's own website.

RULES
- Match the dealership's brand voice (provided as context).
- Use only facts provided. Never invent pricing, financing terms, mileage, or features.
- Keep it under 150 words. Plain text. No markdown headers.
- Always sign off with the dealership name and (if provided) salesperson name.
- Never promise refunds, guarantees, or specific APRs in writing.
- Do not include disclaimers like "*** auto-generated by AI ***".
- Output ONLY the reply body — no subject line, no preamble.`;

export async function POST(request: NextRequest) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await request.json();
    const inquiry: string = body.inquiry || "";
    const tone: ReplyTone = body.tone || "informative";
    const dealership = body.dealership || {};
    const vehicle = body.vehicle || null;
    const salespersonName: string | undefined = body.salespersonName;

    if (!inquiry.trim()) {
      return NextResponse.json({ error: "inquiry required" }, { status: 400 });
    }

    const apiKey = process.env.KIE_API_KEY;
    if (!apiKey) return NextResponse.json({ error: "API key not configured" }, { status: 500 });

    const contextLines: string[] = [];
    if (dealership?.name) contextLines.push(`Dealership: ${dealership.name}`);
    if (dealership?.contact?.phone) contextLines.push(`Phone: ${dealership.contact.phone}`);
    if (dealership?.contact?.address) contextLines.push(`Address: ${dealership.contact.address}`);
    if (dealership?.local_context?.personality)
      contextLines.push(`Brand voice: ${dealership.local_context.personality}`);
    if (salespersonName) contextLines.push(`Salesperson signing the reply: ${salespersonName}`);
    if (vehicle) {
      const v = vehicle;
      contextLines.push(
        `Vehicle of interest: ${[v.year, v.make, v.model, v.trim].filter(Boolean).join(" ")}` +
          (v.price ? ` at $${Number(v.price).toLocaleString()}` : "") +
          (v.mileage ? ` with ${Number(v.mileage).toLocaleString()} miles` : "") +
          (v.stock_number ? ` (Stock #${v.stock_number})` : "")
      );
    }

    const userPrompt = `CUSTOMER INQUIRY:
"""
${inquiry}
"""

CONTEXT:
${contextLines.join("\n") || "(none)"}

TONE: ${tone}
${TONE_INSTRUCTIONS[tone]}

Write the reply now.`;

    const res = await fetch(KIE_CHAT_URL, {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        reasoning_effort: "low",
      }),
    });

    if (!res.ok) {
      const errText = await res.text();
      return NextResponse.json({ error: `Reply generation failed: ${errText}` }, { status: 502 });
    }

    const data = await res.json();
    const content: string = data.choices?.[0]?.message?.content ?? "";
    return NextResponse.json({ reply: content.trim(), tone });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to draft reply";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
